import { Network, NetworkConfig } from "./types";
export declare const NETWORKS: Record<Network, NetworkConfig>;
export declare const DEFAULT_NETWORK: Network;
export declare const CFC_TOKEN_SYMBOL = "CFC";
export declare const CFC_TOKEN_NAME = "CFC";
export declare const CFC_TOKEN_DECIMALS = 18;
export declare const TRUST_SCORE_MIN = 0;
export declare const TRUST_SCORE_MAX = 100;
export declare const TRUST_SCORE_DEFAULT = 50;
export declare const MATCH_SCORE_THRESHOLD = 0.5;
export declare const MAX_MATCHES_PER_DAY = 20;
export declare const MAX_VOTES_PER_USER = 8;
export declare const REPUTATION_MIN_SCORE = 1;
export declare const REWARD_DNA_VERIFICATION = 100;
export declare const REWARD_STD_VERIFICATION = 50;
export declare const GIFT_TOKEN_COST = 1;
export declare const IPFS_GATEWAY = "https://ipfs.io/ipfs/";
export declare const ARWEAVE_GATEWAY = "https://arweave.net/";
export declare const P2P_DISCOVERY_INTERVAL = 30000;
export declare const P2P_HEARTBEAT_INTERVAL = 60000;
export declare const P2P_MESSAGE_TIMEOUT = 10000;
export declare const MAX_MESSAGES_PER_MINUTE = 30;
export declare const MAX_PROFILE_UPDATES_PER_DAY = 10;
export declare const ONE_MINUTE: number;
export declare const ONE_HOUR: number;
export declare const ONE_DAY: number;
export declare const ONE_WEEK: number;
export declare const ONE_MONTH: number;
//# sourceMappingURL=constants.d.ts.map
